terraform {
  source = "."
}

include "ensure_nodes_inputs" {
  # Generated by `cephtools testenv ensure-nodes` to allow rerunning/destroying without re-supplying vars.
  path = "${get_terragrunt_dir()}/ensure-nodes.hcl"
}
